### ISSUE TITLE
forceSsl dont support subdomain

### ISSUE THREAD

**Issue by espensgr** [selvinortiz/craft.patrol#12]
Hey.
I have my page on a subdomain to test the site on the server, but since the plugin uses the getServerName() it is redirected to the main domain. Any possibility to get it to use HTTP_HOST instead or another fix for it?

**Comment by selvinortiz** [comment]
Definitely. Give me a couple of days to work on this, gotta get a few other projects off my plate first.

**Comment by selvinortiz** [comment]
Hi @espensgr,
I'm sorry for the delay in trying to get this issue, I've been swamped with work and haven't had any time to work on my plugins.

Anyway, I wanted to let you know that I've just added this to my breeze project and will be getting fixed before next week hopefully.

**Comment by espensgr** [comment]
Hey!
Any progress on this one?

**Comment by selvinortiz** [comment]
Hi @espensgr, I have been unable to reproduce the issue.

I have a testing server running on a subdomain and `getServerName()` returns the same thing `HTTP_HOST` would return.

Would you be able to record a quick screencast illustrating how Patrol is failing on your subdomain setup? If you could do that, I'll definitely get on it myself or have one of my guys get it patched.

**Comment by selvinortiz** [comment]
Hey @espensgr,
Would it help to have a setting so that you can set that value explicitly in the Control Panel or the file config?

**Comment by espensgr** [comment]
hey @selvinortiz.
Have had some problems reproducing the issue my self, but i can see if i can give it a try again.
Yeah that might help.
