### ISSUE TITLE
Does not work in CP?

### ISSUE THREAD

**Issue by migswd** [selvinortiz/craft.patrol#13]
Hi. I just tried your great plugin for my server for a maintenance operation. But I can still login and use the CP with a user profile that should not be able to do it (Patrol checkbox is not clicked in profile rights).
Did I forget someting to add in the config files ?

**Comment by selvinortiz** [comment]
Hi, if the user is an admin, he/she will be allowed in even if that permission is not checked for the user. The permission is meant for non-admins.

If the user account you logged in with is not an admin, then that's probably something I need to look into.

**Comment by selvinortiz** [comment]
One more thing... the CP is not affected during maintenance mode, only the front end to avoid lockouts.

**Comment by migswd** [comment]
Yes thats the point. I warn people in advance for a maintenance operation but I got many users on CP side so I d like them to be disconnecter automatically before there happen some weird things when they are in the middle of modifications...

**Comment by selvinortiz** [comment]
Hey @migswd, sorry I didn't follow up sooner but it's still unclear to me what the idea. workflow would be for you. Do you feel that Patrol should protect the CP as well? Maybe have a config for that?

**Comment by migswd** [comment]
Hi.
Yes CP too. 

I have 50 users in BO in CP using the website anytime, so it would be cool to be able to warn the guys and disconnect the automatically, after some email warning of course. But sometime some people do not see the email…

But I dont know if it can be possible.

Miguel Bocquier
miguel@silkwormdream.com
http://silkwormdream.com
06 51 40 01 80

**Comment by selvinortiz** [comment]
@migswd While this is possible and probably non trivial to achieve, I don't think I'll be able to get to it until I update the plugin for Craft 2.5.

**Comment by selvinortiz** [comment]
I'm gonna leave this one for Craft 3.0 because as of right now, nobody else is hitting this edgecase.
