### ISSUE TITLE
Plugin not compatible with yiic

### ISSUE THREAD

**Issue by timeverts** [selvinortiz/craft.patrol#14]
When the Patrol plugin is installed in a Craft 2.4 instance and the yiic console command is issued (`craft/app/etc/console/yiic`), the following error is thrown:

`CHttpRequest is unable to determine the request URI.
in /home/teverts/web/mysite.dev/craft/app/etc/errors/ErrorHandler.php (95)
exception 'CException' with message 'CHttpRequest is unable to determine the request URI.' in /home/teverts/web/mysite.dev/craft/app/framework/web/CHttpRequest.php:554
Stack trace:
#0 /home/teverts/web/mysite.dev/craft/app/framework/web/CHttpRequest.php(320): CHttpRequest->getRequestUri()

#1 /home/teverts/web/mysite.dev/craft/plugins/patrol/services/PatrolService.php(45): CHttpRequest->getUrl()

#2 /home/teverts/web/mysite.dev/craft/plugins/patrol/services/PatrolService.php(29): Craft\PatrolService->protect(Array)

#3 /home/teverts/web/mysite.dev/craft/plugins/patrol/PatrolPlugin.php(44): Craft\PatrolService->watch(Array)

#4 /home/teverts/web/mysite.dev/craft/app/services/PluginsService.php(138): Craft\PatrolPlugin->init()

#5 /home/teverts/web/mysite.dev/craft/app/etc/console/ConsoleApp.php(80): Craft\PluginsService->loadPlugins()

#6 /home/teverts/web/mysite.dev/craft/app/framework/base/CApplication.php(169): Craft\ConsoleApp->init()

#7 /home/teverts/web/mysite.dev/craft/app/framework/YiiBase.php(121): CApplication->__construct('/home/teverts/w...')

#8 /home/teverts/web/mysite.dev/craft/app/etc/console/yiic.php(78): YiiBase::createApplication('Craft\ConsoleAp...', '/home/teverts/w...')

#9 /home/teverts/web/mysite.dev/craft/app/etc/console/yiic(4): require_once('/home/teverts/w...')

#10 {main}www-data@slave5:/home/teverts/web/mysite.dev`

**Comment by selvinortiz** [comment]
Hi Tim, sorry for the delay response.

I've been seeing a lot of issues like this one coming up on for other plugins as well. I feel like something must have changed about the Craft bootstrapping when running Yii commands or something.

I'll have to take a closer look and see what I can do about this.

**Comment by timeverts** [comment]
I agree. I have also found that the majority of plugins don't account for console access.

But wrapping something like the following around the code in question should get around the issue:
`if (!craft()->isConsole()) { }`

**Comment by selvinortiz** [comment]
@timeverts Totally!

Checking if Craft is being accessed in console context on the `init()` method would definitely be the way to go. I'd be happy to accept a pull request; )

**Comment by selvinortiz** [comment]
This was fixed in the last release https://github.com/selvinortiz/craft.patrol/releases/tag/v1.1.1
