### ISSUE TITLE
Block all users (including admins)

### ISSUE THREAD

**Issue by timkelty** [selvinortiz/craft.patrol#19]
A frequent scenario for a site in development is:
- multiple admins are working on site
- a dev (me) will needs to shut everyone out temporarily while I pull the database down locally and do something.

Is there anyway to achieve this with Patrol? It seems like admins can always log in, but I guess I'm looking for a way to block everyone (obviously this would need to be done via config and not in the CP).

**Comment by madebyshape** [comment]
+1

**Comment by selvinortiz** [comment]
@timkelty @madebyshape One way of adding this functionality might be to add another setting (`Restrict Admins` off by default) that lets Patrol know to **only** authorize people with the `Patro > Access the site when maintenance is on` permission.

Would that cover your use cases or not?

**Comment by timkelty** [comment]
@selvinortiz I think it would!

**Comment by selvinortiz** [comment]
@timkelty On second thought, it might be better to have a `content freeze mode` or `quarantine mode` that blocks all users except those that are admins *and* have permission to _access the site when maintenance is no_.

What do you think?

**Comment by madebyshape** [comment]
Content Freeze is a good shout. It would be good to make sure content can't be added / edited, but viewed - along with a message of when they are able to access the edit the site again. 

Blocking users out of the CMS could be quite annoying especially if they only want to just check something.

The only other issue is if forms are submitted or even products placed on the front end that make the database out of sync?

**Comment by timkelty** [comment]
@selvinortiz Yeah that seems more flexible.

However, with the added complexity - I think you'll want to make sure its clear what the admin should expect. Ideally it would be clear enough from the config settings/options that the admin would be confident enough, and wouldn't have to log in as a non-admin to make sure it was working :)

Since this feature _really_ only makes sense when 1 dev is pulling the site down, I might actually prefer an explicit setting like:

```
[
  'patrol' => [
    'maintenanceMode' => true,
    'authorizedUsers' => [
      'tim@fusionary.com',
    ],
  ],
]
```

`authorizedUsers` would be `null` by default, `array()` would be no access for anyone.

**Comment by selvinortiz** [comment]
@madebyshape I think `content freeze` is the wrong framing, I definitely don't want Patrol to do any more than simple SSL and maintenance routing.

@timkelty I totally understand and I think you're right, for a feature like this, you have to make it clear what's going on. I'll have to do a little more thinking though because I don't like having an `authorizedUsers` setting that goes through different logic branches based on whether is `null`, is empty `array` or `has data`.

**Comment by timkelty** [comment]
@selvinortiz ok, I'll keep thinking on it too.

**Comment by selvinortiz** [comment]
@timkelty I think `authorizedUsers` might work if it behaves as follows:

1. Only available via `config/general.php` configs
2. If set to `null` or `[]` it is meaningless
3. If set to `non-empty array` of emails, it blocks everyone but users in that list

> Of course, user(s) in `authorizedUsers` would have to be logged in for Patrol to be able to compare their email address.

**Comment by timkelty** [comment]
@selvinortiz I'm good with that!

**Comment by selvinortiz** [comment]
@timkelty I just realized that most of this only apply to `CP Requests`:) As such, we can have a set of rules for CP requests without really affecting how site requests are currently handled.

**Comment by selvinortiz** [comment]
@timkelty @madebyshape I've gone ahead and implemented this feature in the latest alpha release. Would you be able to check it out and provide some feedback?

All you have to is update your config file to something like:

```php
return [
  // all
  '*' => [
    'patrol' => [
      'maintenance' => true,
      'authorizedUsers' => ['your@mail.com']
    ],
  ],
];
```

By doing this, you're essentially saying that:

> You don't care about who's authorized, either through an admin account or by having the permission or by having their IP whitelisted. If they are not in the `authorizedUsers` array, they won't have access.

I should mention that this only apply to the CP, front-end rules remain the same.

**Comment by timkelty** [comment]
I'll test it out today!

**Comment by timkelty** [comment]
@selvinortiz seems to work well for me!

Anyone copying and pasting from https://github.com/selvinortiz/craft.patrol/issues/19#issuecomment-232741096, the correct setting is `maintenanceMode`, not `maintenance`.

**Comment by selvinortiz** [comment]
@timkelty Great, thanks!

**Comment by timkelty** [comment]
@selvinortiz With your latest alpha, it seems not possible leave the front-end site up, but block users from the cp with `authorizedUsers`. Is that right or is there something I'm missing?

I know I can give members access the front-end by adjusting their permissions, but for guests (non-registered) users it doesn't seem that there is a way.

**Comment by selvinortiz** [comment]
Would IP address whitelisting not work in the case?

**Comment by timkelty** [comment]
I suppose it could, but setting `'authorizedIps' => ['*.*.*.*']` seems pretty roundabout. Plus that doesn't account for ipv6 addresses.

I guess I'd be looking for a `bypassMaintenanceModeForGuests` or something, but that may be just muddying thing further.

Starts to all get a bit confusing, knowing exactly what `maintenanceMode` means (cp, front-end, both?) and who is exempt.

**Comment by selvinortiz** [comment]
I guess I don't really understand when, all users should be blocked but guests be allowed. Sounds to me like you need to block admins without putting the site on maintenance mode.

Currently, authorized users is only checked when maintenance mode is on, maybe that's what needs to change.

**Comment by selvinortiz** [comment]
And yes, using IP whitelisting in that way would be ridiculous. Adding more settings would definitely not help. You're right!

**Comment by timkelty** [comment]
@selvinortiz Yeah, I think I'm definitely trying to wrangle the settings that exist into my use-case, which might not result in the best decisions -- But thanks for working with me!

> Currently, authorized users is only checked when maintenance mode is on, maybe that's what needs to change.

I think that would cover my case. It remains a bit vague as to which settings work for the front-end vs cp and which in tandem with maintenance mode. Ideally, they could all work the same and be self-describing.

Just to sum up, here's ideally the feature I'm looking for:
- deny CP access to all but "specified users" (`authorizedUsers`)
- optionally, leave front-end accessible to non-members/guests

**Comment by selvinortiz** [comment]
@timkelty How about allowing maintenance and SSL routing to behave as it has in the past and rather than using `authorizedUsers`, we introduce a new setting (like `limitCpAccessTo`) that works independently of maintenance configuration?

This way, the behavior of your maintenance and SSL settings does not change. If you want to lock down the CP to pull down the db, make schema changes, or whatever... you can simply populate the `limitCpAccessTo` with your email address or email addresses of users you want to give access to.

```php
return [
  // all
  '*' => [
    'patrol' => [
      'maintenanceMode' => true, // or false (doesn't matter)
      'limitCpAccessTo' => ['your@mail.com']
    ],
  ],
];
```

**Comment by timkelty** [comment]
@selvinortiz That's much more more clear. I like it.

**Comment by timkelty** [comment]
Would also be nice to use `UsersService->getUserByUsernameOrEmail` so you could use username or email!

**Comment by selvinortiz** [comment]
@timkelty Cool.

Getting the user by username or email won't be necessary because the user/admin will need to be logged in to determine eligibility, but it will be nice to be able to use an email or username in the array. I'll make sure that we validate the logged in user by checking if his/her username or email exists on the `limitCpAccessTo` array.

**Comment by madebyshape** [comment]
Just got round to testing this and it does work great, but I don't think turning off the front end is an option. It's more to restrict the admins from editing the site whilst changes to the site are made / deployed.

Adding the `limitCpAccessTo` option would be great!

**Comment by selvinortiz** [comment]
@timkelty @madebyshape Ok, release https://github.com/selvinortiz/craft.patrol/releases/tag/v1.4.1 should get us pretty there.

**Comment by madebyshape** [comment]
Thanks! That seems to do the job, but theres a few confusing things.

- When a user is set in `limitCpAccessTo`, you can't even get to the /admin area to login with that user. It locks all admins out. But, you can get to /admin/login

- It would be good if a different `maintenanceUrl` could be set for the users that are not allowed to login. This way when a user tries to login via the CMS, we could explain to them that Control Panel access is restricted etc. Which I can't put in the `maintenanceUrl` template.

But, it does work!

**Comment by selvinortiz** [comment]
@madebyshape Thanks for the report. Hitting `admin/login` was supposed to work but it looks like there is a little bug where the `/login` segment is not properly matched. Fixing that would essentially fix the issue you brought up.

As for a specific maintenance URL: I rather throw a `403` or in your maintenance page, you could check if the user is logged in and is an admin, that way you can respond accordingly. Provided the login issue is fixed:)

**Comment by madebyshape** [comment]
Gotcha! Didn't even think about putting that logic in to the template DOH! Will do just that.

With the `/admin/login` issue, it does allow me to access this, but most of our clients go to `/admin` and it doesn't auto redirect to `/admin/login` for them to sign in, it just shows the maintenance page. If they could still access this page and then only show the error once they have logged in that would be better.

**Comment by selvinortiz** [comment]
I see, I'll have to look into that as soon as I get a chance, it's been a busy season.

**Comment by selvinortiz** [comment]
@madebyshape Just wanted to let you know that I haven't forgotten about this, just been busy. I plan on looking at it after the holidays.

**Comment by selvinortiz** [comment]
@madebyshape Patrol should now redirect to `/{cpTrigger/login` automatically when using `limitCpAccessTo`👍
