### ISSUE TITLE
Use config.php

### ISSUE THREAD

**Issue by timkelty** [selvinortiz/craft.patrol#20]
Since 2.0.2524, plugins can have their own config.php file instead of sharing with general.php.
Would be nice to get set these in their own config.php, (then overridable by a user craft/config/patrol.php)

**Comment by selvinortiz** [comment]
@timkelty I'm not sure I'll get to this prior to a (planned) major release for Craft 3. Happy to consider a _pull request_ though😉

**Comment by timkelty** [comment]
That's what I figured :). I mostly made the issue to remind myself to PR, but will probably just wait for a Craft 3 version.

**Comment by selvinortiz** [comment]
@timkelty Cool, I'll leave the issue open then.

**Comment by selvinortiz** [comment]
@timkelty I almost tackled this today but I realized that if I didn't want to force users to move their configs in `config/general.php` to `config/patro.lphp`, I had to add backwards compatibility supports and while not difficult, I decided that I'll just that for the Craft 3 version.

**Comment by timkelty** [comment]
Sounds good.
