### ISSUE TITLE
Request: URL with code to access. 

### ISSUE THREAD

**Issue by shornuk** [selvinortiz/craft.patrol#23]
Hi, looking at using Patrol thanks to it's environment settings. Very useful. 
One thing that would be great if it could be implemented is the ability to generate a url with a code so that it can be sent to someone to access whilst the sites offline. 
IP Whitelist for Craft does this. Typically we want to keep our staging sites in maintenance mode, but it would be great if we could send a client a link that adds there IP to the permitted list.

**Comment by selvinortiz** [comment]
Hi @shornuk,
So, this would be an additional authentication method to allow users to access the site by hitting a specific URL with a token/code parameter.

I like it👍

We're talking about simple token based authentication, right?

Meaning, you have the right param in the URL, your IP gets added to the whitelist, and you're in.

We don't have to handle single-use tokens/codes, or token/code expiration, correct?

**Comment by shornuk** [comment]
That's it! Yea, just a simple means of allowing some to get access with a link, and like you said, they then get added to the list. This has worked quite nicely in past with clients. Saves going through a process of trying to get them to find there IP address and send it over.

**Comment by selvinortiz** [comment]
Hey @shornuk after thinking through this some more and realizing how limited my time is, I decided that your feature request would be really useful and I plan to add it to Patrol for Craft 3.

However, for the Craft 2 version of Patrol, I'm gonna have to hold off. I'm sorry about that, I just don't have enough time to tackle it and I have to pick my battles.

-Selvin O.

**Comment by shornuk** [comment]
No probs and understandable! 👍🏼
